name: food_order_ui
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  lottie: ^3.1.2
  curved_navigation_bar: ^1.0.3
  carousel_slider: ^4.0.0
  get: ^4.6.6
  http: ^1.2.0
  shared_preferences: ^2.2.2
  image_picker: ^0.8.4+11
  file_picker: ^4.0.0
  fl_chart: ^0.35.0
  syncfusion_flutter_charts: ^20.1.54
  dart_jsonwebtoken: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0 # Updated version

flutter:
  uses-material-design: true

  assets:
    - assets/category/
    - assets/discount/
    - assets/food/
    - assets/main/
